title: Hello World
author: zrma
email: bulbitain@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hahaha....

# social links
github_username:  zrma

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
